### ISSUE TITLE
Global State in React.js

### ISSUE THREAD

**Issue by Gautam-Arora24** [Gautam-Arora24/typing-frenzy#1]
Add a global state in the application for Timer. You can ask me about the code structure. Feel free to ask any doubts.

**Comment by SahilKumar47** [comment]
I would like to work on this

**Comment by Gautam-Arora24** [comment]
Yaa sure.

**Comment by Gautam-Arora24** [comment]
Basically what I want is that there should be a global state (using Context) and all the routes can access it for the timer I implemented in the code

**Comment by SahilKumar47** [comment]
can I use redux instead of context ?

**Comment by Gautam-Arora24** [comment]
I have to close this issue for some reasons
